name: TestEnv
on:
  push:
    branches: [main-platform]
permissions: write-all
env:
  CARGO_TERM_COLOR: always
  TEST_VAR: hello
jobs:
  t:
    runs-on: ubuntu-latest
    steps:
      - run: echo "$TEST_VAR env test"
